version: '3.7'

services:
  rotatter:
    image: ciffelia/rotatter
    build: .
    restart: always
    init: true
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_ACCESS_TOKEN_KEY
      - TWITTER_ACCESS_TOKEN_SECRET
