name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: yarn run lint

  build-docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: docker-compose build
