name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run lint

  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose build
